#!/bin/bash

if ! test -f version.h
then

cat << EOT > version.h
#ifndef __VERSION_GIT_AUTOGEN_H__
#define __VERSION_GIT_AUTOGEN_H__

/* this file autogenerated by git-ex-version.sh */

/* you can define your own version without git */
#ifndef VERSION_NO
EOT

TAG=`git tag | grep "^v" | tail -1`

if test -z "$TAG"
then
	echo "#define VERSION_NO \"vX.X\"" >> version.h
else
	echo "#define VERSION_NO \"$TAG\"" >> version.h
fi

cat << EOT >> version.h
#endif
#endif
EOT

fi
