#ifndef __VERSION_GIT_AUTOGEN_H__
#define __VERSION_GIT_AUTOGEN_H__

/* this file autogenerated by git-ex-version.sh */

/* you can define your own version without git */
#ifndef VERSION_NO
#define VERSION_NO "v2.0"
#endif
#endif
